[settings]
experimental = true

[tools]
"rust" = { version = "1.97.1", profile = "default" }
"node" = "24.20.0"
"hk" = "latest"
"pkl" = "latest"
"cargo:cargo-llvm-cov" = "latest"
"cargo:cargo-deny" = "latest"

[hooks]
postinstall = "hk install --mise"
