[settings]
experimental = true

[tools]
"rust" = { version = "1.93.0", profile = "default" }
"hk" = "latest"
"pkl" = "latest"
"github:boykush/scraps" = "v1.0.1"
"npm:markdownlint-cli2" = "latest"
"cargo:cargo-llvm-cov" = "latest"
"cargo:cargo-deny" = "latest"
"zizmor" = "1.25.2"

[hooks]
postinstall = "hk install --mise"
