#[cfg(feature = "git")]
pub mod git;
#[cfg(feature = "markdown")]
pub mod markdown;
#[cfg(feature = "model")]
pub mod model;
#[cfg(feature = "slugify")]
pub mod slugify;
#[cfg(feature = "test_supports")]
pub mod tests;
