name: Claude Code Actions

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  claude-code:
    if: |
      github.event.comment.user.login == 'boykush' && (
        (github.event_name == 'issue_comment' && github.event.issue.pull_request) ||
        github.event_name == 'pull_request_review_comment'
      )
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      issues: write
      
    steps:
      - name: Verify user authorization
        run: |
          echo "✅ Authorized user: ${{ github.event.comment.user.login }}"
          if [ "${{ github.event.comment.user.login }}" != "boykush" ]; then
            echo "❌ Unauthorized user attempted to trigger Claude Code Actions"
            exit 1
          fi
      
      - name: Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}