name: Deploy scraps github pages
on: 
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-scraps-github-pages.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # For scraps git commited date
      - name: build_and_deploy
        uses: boykush/scraps-deploy-action@fb0c9aa408b81b7a45f00329c92054a26e0e8333 # v4.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pages-branch: gh-pages
